# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

# Generated by Django 5.1.5 on 2025-01-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("invalid", "Invalid"),
                    ("failed", "Failed"),
                    ("published", "Published"),
                ],
                max_length=50,
            ),
        ),
    ]
