#!/bin/sh

set -xe

"$SNAP/bin/prepare"

# Create some directories
mkdir -p "$SNAP_COMMON/app"

# set default configuration values
snapctl set django-debug='false'
snapctl set django-allowed-hosts='["localhost", "127.0.0.1", "0.0.0.0"]'
