# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
options:
  public-ips:
    description: A comma separated list of public IPs at which bind units are reachable.
    type: string
    default: ""
  names:
    description: A comma separated list of names for this server.
    type: string
    default: ""
  mailbox:
    description: |
      Mailbox to use to contact the zone administrator as per RFC2142
    default: "hostmaster"
    type: string
