# Generated by Django 5.1.4 on 2025-01-10 20:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordRequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("host_label", models.CharField(max_length=255)),
                ("ttl", models.IntegerField(null=True)),
                ("record_type", models.CharField(max_length=10)),
                ("record_data", models.CharField(max_length=255)),
                ("requirer_id", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=50)),
                ("status_reason", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_modified_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
