# Generated by Django 5.1.4 on 2025-01-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0002_auto_20250110_2028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordrequest",
            name="requirer_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
