name: Charmed-dns-policy tests

on:
  pull_request:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set directory
        env:
          DIRECTORY: ./charmed-dns-policy
          BASE: ${{ github.event.pull_request.base.sha }}
        run: |
          if [ -n "$(git diff $BASE..HEAD -- $DIRECTORY)" ]; then
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi
        id: changes
    outputs:
      changed: ${{ steps.changes.env.CHANGED }}

  django-tests:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'
    services:
      postgres:
        image: postgres@sha256:1c47b7139517eeb5e9747882983297a745517c3d70d2451e376f9fd5cc7cf1ef
        env:
          POSTGRES_PASSWORD: testpassword
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd ./charmed-dns-policy/app
          python3 -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          export $(xargs < ci/.test-env) && ./manage.py test

  ruff:
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install ruff

      - name: Run Ruff
        run: |
          ruff check charmed-dns-policy/app/
