name: Load tests

on:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  load-tests-bind-operator:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    with:
      load-test-enabled: false
      load-test-run-args: "-e LOAD_TEST_HOST=localhost"
      working-directory: ./bind-operator
    secrets: inherit
