name: Promote bind operator

on:
  workflow_dispatch:
    inputs:
      origin-channel:
        type: choice
        description: 'Origin Channel'
        options:
        - latest/edge
      destination-channel:
        type: choice
        description: 'Destination Channel'
        options:
        - latest/stable
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  promote-charm-bind-operator:
    uses: canonical/operator-workflows/.github/workflows/promote_charm.yaml@main
    with:
      origin-channel: ${{ github.event.inputs.origin-channel }}
      destination-channel: ${{ github.event.inputs.destination-channel }}
      working-directory: ./bind-operator
    secrets: inherit
