name: Publish charmed-dns-policy to edge

on:
  workflow_dispatch:
    secrets:
      SNAP_STORE_TOKEN:
        required: true

jobs:
  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v31.0.1
    with:
      path-to-snap-project-directory: ./charmed-dns-policy

  release:
    name: Release snap
    needs:
      - build
    steps:
      - name: Install snapcraft
        run: sudo snap install snapcraft --classic
      - run: snap list
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download snap package(s)
        uses: actions/download-artifact@v4.2.1
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true
      - name: Publish the snap
        run: |
          cd ./charmed-dns-policy
          snapcraft upload --release="latest/edge" charmed-dns-policy_*.snap
        env:
          SNAPCRAFT_STORE_AUTH: candid
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_TOKEN }}
