name: Publish dns-integrator-operator to edge

on:
  workflow_dispatch:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up environment
        run: |
          sudo snap install lxd
          sudo adduser "$USER" lxd
          # `newgrp` does not work in GitHub Actions; use `sudo --user` instead
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd waitready
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd init --auto
          # Workaround for Docker & LXD on same machine
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT
          sudo snap install charmcraft --classic
      - run: snap list
      - name: Pack, upload and release charm
        run: |
          cd ./dns-integrator-operator
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- charmcraft pack -v
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- charmcraft upload *.charm --format json > .upload_results
          jq -r . .upload_results  # print result (for debugging)
          revision="$(jq -rc '.revision' .upload_results)"
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- charmcraft release dns-integrator --channel=latest/edge --revision="$revision"
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
