name: Publish charmed-dns-policy to edge

on:
  workflow_dispatch:
    secrets:
      SNAP_STORE_TOKEN:
        required: true

jobs:
  publish:
    name: Release snap
    runs-on: ubuntu-latest
    steps:
      - name: Install snapcraft
        run: sudo snap install snapcraft --classic
      - run: snap list
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and publish the snap
        run: |
          cd ./charmed-dns-policy
          snapcraft --verbose
          snapcraft upload --release="latest/edge" charmed-dns-policy_*.snap
        env:
          SNAPCRAFT_STORE_AUTH: candid
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_TOKEN }}
